version: "3.8"

services:
  osu.tools:
    image: osu.tools
    stdin_open: true
    container_name: osu.tools
    build:
      context: .
      dockerfile: shell.Dockerfile
      args:
        - OSU_GIT=${OSU_GIT}
        - OSU_GIT_BRANCH=${OSU_GIT_BRANCH}
        - OSU_TOOLS_GIT=${OSU_TOOLS_GIT}
        - OSU_TOOLS_GIT_BRANCH=${OSU_TOOLS_GIT_BRANCH}

  osu.tools.gui:
    image: osu.tools.gui
    stdin_open: true
    container_name: osu.tools.gui
    build:
      context: .
      dockerfile: gui.Dockerfile
      args:
        - OSU_GIT=${OSU_GIT}
        - OSU_GIT_BRANCH=${OSU_GIT_BRANCH}
        - OSU_TOOLS_GIT=${OSU_TOOLS_GIT}
        - OSU_TOOLS_GIT_BRANCH=${OSU_TOOLS_GIT_BRANCH}
