version: "0.1"

services:
  tools-service:
    image: tools
    stdin_open: true
    container_name: osu-tools
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GITHUB_USERNAME=${GITHUB_USERNAME}
        - GITHUB_BRANCHNAME=${GITHUB_BRANCHNAME}
