version: "0.1"

services:
  tools-service:
    image: tools
    stdin_open: true
    container_name: osu-tools
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - OSU_GIT=${OSU_GIT}
        - OSU_GIT_BRANCH=${OSU_GIT_BRANCH}
        - OSU_TOOLS_GIT=${OSU_TOOLS_GIT}
        - OSU_TOOLS_GIT_BRANCH=${OSU_TOOLS_GIT_BRANCH}
